name: spots2reciprocal
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.3.2
  - numpy=1.19.2
  - pip=20.2.4
  - python=3.7.4
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - ipython
  - jupiterlab
  - ase